### PR TITLE
Add gof3r to have proper path-style support for S3 compatible endpoints.

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by mgolisch** [comment]
+1
would be great for using gof3r with s3 compatible things like minio.

**Comment by harshavardhana** [comment]
Is there any needed from our end @rlmcpherson PR, please do let us know?

**Comment by harshavardhana** [comment]
Just checking back again if there is anything needed @rlmcpherson to get this included in gof3r

**Comment by delgod** [comment]
@rlmcpherson any change to get it merged?

**Comment by harshavardhana** [comment]
I closed it since there was no response for over 2 yrs.

**Pull request closed without merging**
